import React, { useState } from "react";
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  RadioGroup,
  Radio,
  FormControlLabel,
  Box,
  Divider,
  IconButton,
} from "@mui/material";
import { Close, Print, FileDownload } from "@mui/icons-material";

const ALL_COLUMNS = [
  { key: "supplier_id", label: "ID" },
  { key: "supplier_name", label: "Supplier Name" },
  { key: "address", label: "Address" },
  { key: "contact_no", label: "Contact No." },
  { key: "other_details", label: "Other Details" },
];

const COMPANY_NAME = "Kimwin Corporation";
const COMPANY_SUBTITLE = "Suppliers List";

export default function PrintSuppliersModal({
  open,
  handleClose,
  suppliers, // all filtered suppliers
  selectedIds = [], // currently selected supplier ids
  hasSelection = false, // whether selection mode is active w/ items selected
}) {
  const [scope, setScope] = useState(hasSelection ? "selected" : "all");

  // Keep scope option in sync each time modal opens
  React.useEffect(() => {
    if (open) setScope(hasSelection ? "selected" : "all");
  }, [open, hasSelection]);

  const getDataToExport = () => {
    if (scope === "selected") {
      return suppliers.filter((s) => selectedIds.includes(s.supplier_id));
    }
    return suppliers;
  };

  const buildPrintHtml = (data, cols) => {
    const printDate = new Date().toLocaleString("en-PH", {
      month: "long",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

    const headerCells = cols.map((c) => `<th>${c.label}</th>`).join("");

    const rows = data
      .map((s, i) => {
        const cells = cols.map((c) => `<td>${s[c.key] ?? "—"}</td>`).join("");
        return `<tr><td>${i + 1}</td>${cells}</tr>`;
      })
      .join("");

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${COMPANY_NAME} - Suppliers List</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
              font-family: Arial, sans-serif;
              font-size: 11px;
              color: #111;
              padding: 24px;
              display: flex;
              justify-content: center;
            }
            .sheet {
              width: 100%;
              max-width: 820px;
            }
            .company-header {
              text-align: center;
              margin-bottom: 18px;
              padding-bottom: 14px;
              border-bottom: 3px solid #ef7d14;
            }
            .company-header h1 {
              font-size: 22px;
              font-weight: bold;
              letter-spacing: 0.04em;
              color: #111;
              text-transform: uppercase;
            }
            .company-header .doc-title {
              font-size: 13px;
              font-weight: bold;
              color: #ef7d14;
              text-transform: uppercase;
              letter-spacing: 0.1em;
              margin-top: 4px;
            }
            .sub {
              font-size: 10px;
              color: #666;
              margin-bottom: 16px;
              text-align: center;
            }
            table { width: 100%; border-collapse: collapse; }
            th {
              background: #ef7d14;
              color: #fff;
              text-align: left;
              padding: 7px 10px;
              font-size: 10px;
              text-transform: uppercase;
              letter-spacing: 0.05em;
            }
            td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
            tr:nth-child(even) td { background: #fafafa; }
            tr:last-child td { border-bottom: none; }
            .footer { margin-top: 20px; font-size: 9px; color: #999; text-align: right; }
            @media print {
              body { padding: 0; justify-content: center; }
              @page { margin: 16mm; }
            }
          </style>
        </head>
        <body>
          <div class="sheet">
            <div class="company-header">
              <h1>${COMPANY_NAME}</h1>
              <div class="doc-title">${COMPANY_SUBTITLE}</div>
            </div>

            <p class="sub">
              Printed on ${printDate} &nbsp;·&nbsp; ${data.length} supplier${data.length !== 1 ? "s" : ""}
              ${scope === "selected" ? " (selected only)" : ""}
            </p>

            <table>
              <thead><tr><th>#</th>${headerCells}</tr></thead>
              <tbody>${rows}</tbody>
            </table>

            <p class="footer">Generated by Inventory System</p>
          </div>
        </body>
      </html>`;
  };

  const handlePrint = () => {
    const data = getDataToExport();
    if (data.length === 0) return;

    const html = buildPrintHtml(data, ALL_COLUMNS);

    // Center the popup window on screen instead of top-left
    const width = 900;
    const height = 700;
    const left = Math.max(
      0,
      (window.screen.width - width) / 2 +
        (window.screenLeft ?? window.screenX ?? 0),
    );
    const top = Math.max(
      0,
      (window.screen.height - height) / 2 +
        (window.screenTop ?? window.screenY ?? 0),
    );

    const win = window.open(
      "",
      "_blank",
      `width=${width},height=${height},left=${left},top=${top}`,
    );
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
    win.close();

    handleClose();
  };

  const escapeCsv = (value) => {
    const str = String(value ?? "");
    if (/[",\n]/.test(str)) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const handleExportCsv = () => {
    const data = getDataToExport();
    if (data.length === 0) return;

    const headerRow = ["#", ...ALL_COLUMNS.map((c) => c.label)].join(",");
    const dataRows = data.map((s, i) =>
      [i + 1, ...ALL_COLUMNS.map((c) => escapeCsv(s[c.key]))].join(","),
    );
    const csvContent = [headerRow, ...dataRows].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const dateStr = new Date().toISOString().slice(0, 10);
    link.href = url;
    link.download = `suppliers_${dateStr}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    handleClose();
  };

  const selectedCount = selectedIds.length;
  const isDisabled = scope === "selected" && selectedCount === 0;

  return (
    <Dialog open={open} onClose={handleClose} fullWidth maxWidth="sm">
      <DialogTitle
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          fontWeight: "bold",
        }}
      >
        Print / Export Suppliers
        <IconButton onClick={handleClose} size="small">
          <Close fontSize="small" />
        </IconButton>
      </DialogTitle>

      <Divider />

      <DialogContent>
        <Typography variant="subtitle2" fontWeight="bold" sx={{ mb: 1 }}>
          Scope
        </Typography>
        <RadioGroup value={scope} onChange={(e) => setScope(e.target.value)}>
          <FormControlLabel
            value="all"
            control={<Radio />}
            label="All suppliers"
          />
          <FormControlLabel
            value="selected"
            control={<Radio />}
            label={`Selected only (${selectedCount})`}
            disabled={selectedCount === 0}
          />
        </RadioGroup>

        {isDisabled && (
          <Typography variant="caption" color="error">
            No suppliers selected. Switch to "All suppliers" or select rows
            first.
          </Typography>
        )}
      </DialogContent>

      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Box sx={{ flexGrow: 1 }} />
        <Button
          variant="outlined"
          startIcon={<FileDownload />}
          onClick={handleExportCsv}
          disabled={isDisabled}
          sx={{ textTransform: "none", fontWeight: "bold" }}
        >
          Export CSV
        </Button>
        <Button
          variant="contained"
          startIcon={<Print />}
          onClick={handlePrint}
          disabled={isDisabled}
          sx={{
            textTransform: "none",
            fontWeight: "bold",
            bgcolor: "#ef7d14",
            "&:hover": { bgcolor: "#d66e0f" },
          }}
        >
          Print
        </Button>
      </DialogActions>
    </Dialog>
  );
}
